services:
  pocketbase:
    build: .
    ports:
      - 8080:8080
    volumes:
      - ./data:/pb/pb_data
      - ./docker/migrations:/pb/pb_migrations
    env_file: .env
  vite:
    build:
      context: ./spa
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./spa:/app
      - /app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"
    env_file: ./spa/.env
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    depends_on:
      - pocketbase
